spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb+srv://dolaoye:2ArPEPZSdrP9cy7J@cluster1.mx2a8.mongodb.net/demo?retryWrites=true&w=majority&appName=Cluster1

graphql:
  packages: "com.example.demographql"
  server:
    enabled: true
    endpoint: "/graphql"
  playground:
    enabled: true
